### ISSUE TITLE
Navigation-Highlight

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/navigation-highlight#1]
@thomasjbradley
I'm not quite sure on how to make the Markbot practice images match with my website. I tried different ideas, however, it seems that my problem can't be solved.

**Comment by thomasjbradley** [comment]
Let’s start by deleting a bunch of unnecessary CSS:

Delete the following lines:
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L3
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L6-L7
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L16-L17
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L20
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L33
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L54
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L58-L59
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L78

We should not repeat all the CSS—the same CSS should work for every page, so all of this is just making it more difficult to debug:
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L87-L98
- https://github.com/Sophia-Villamayor/navigation-highlight/blob/gh-pages/css/main.css#L105-L163
